### ISSUE TITLE
Error pip install -r requires.dev.txt

### ISSUE THREAD

**Issue by baditaflorin** [geometalab/OSM-Crosswalk-Detection#75]
pip install -r requires.dev.txt
Collecting autopep8 (from -r requires.dev.txt (line 1))
/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading autopep8-1.2.4-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 1.2MB/s 
Collecting click (from -r requires.dev.txt (line 2))
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 2.0MB/s 
Collecting coverage (from -r requires.dev.txt (line 3))
  Downloading coverage-4.1.tar.gz (370kB)
    100% |████████████████████████████████| 378kB 1.7MB/s 
Collecting django-environ (from -r requires.dev.txt (line 4))
  Downloading django-environ-0.4.0.tar.gz
Collecting fake-useragent (from -r requires.dev.txt (line 5))
  Downloading fake-useragent-0.0.8.tar.gz
Collecting flake8 (from -r requires.dev.txt (line 6))
  Downloading flake8-2.5.4-py2.py3-none-any.whl
Collecting geopy (from -r requires.dev.txt (line 7))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 12.4MB/s 
Collecting h5py (from -r requires.dev.txt (line 8))
  Downloading h5py-2.6.0.tar.gz (245kB)
    100% |████████████████████████████████| 245kB 4.1MB/s 
    Complete output from command python setup.py egg_info:
    no previously-included directories found matching 'doc/.build'
    
    Installed /tmp/easy_install-pMptI7/pkgconfig-1.1.0/.eggs/nose-1.3.7-py2.7.egg
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-build-5_aJV6/h5py/.eggs/pkgconfig-1.1.0-py2.7.egg
    Searching for Cython>=0.19
    Reading https://pypi.python.org/simple/Cython/
    Best match: Cython 0.24
    Downloading https://pypi.python.org/packages/b1/51/bd5ef7dff3ae02a2c6047aa18d3d06df2fb8a40b00e938e7ea2f75544cac/Cython-0.24.tar.gz#md5=14fbc970f4a856845e633cbc09e61048
    Processing Cython-0.24.tar.gz
    Writing /tmp/easy_install-BihaDE/Cython-0.24/setup.cfg
    Running Cython-0.24/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BihaDE/Cython-0.24/egg-dist-tmp-Zv66N1
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    /tmp/easy_install-BihaDE/Cython-0.24/Cython/Plex/Scanners.c:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    Unable to find pgen, not compiling formal grammar.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5_aJV6/h5py/setup.py", line 149, in <module>
        cmdclass = CMDCLASS,
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5_aJV6/h5py/

**Comment by marcelhuberfoo** [comment]
I updated the 'install locally' section to list some of the required packages and placed a note to check within the Dockerfiles to find the complete list of requirements.
